Style/Documentation:
 Enabled: false

Style/ClassAndModuleChildren:
  EnforcedStyle: compact
  Exclude:
    - 'config/application.rb'

AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'bin/**/*'
    - 'vendor/bundle/**/*'
